###  持有期收益率计算

In [1]:
import pandas as pd

In [2]:
dfprice = pd.read_excel('企业债价格.xlsx',header = 1)
dfprice.Date = dfprice.Date.astype(str).apply(lambda x:x[:-3])
dfprice.set_index('Date',inplace = True)

In [3]:
df_interestpay = pd.read_excel('企业债付息日和付息率2.xlsx')
df_interestpay.columns = ['证券代码', '证券简称', '利率说明', '付息日','起息日']
df_interestpay.set_index('证券代码',inplace = True)

In [4]:
df_net_price = pd.read_excel('债券净值.xlsx',header = 1)
df_net_price.Date = df_net_price.Date.astype(str).apply(lambda x:x[:-3])
df_net_price.set_index('Date',inplace = True)

### 制作利率的模板

In [5]:
df_interestpay['len'] = df_interestpay['利率说明'].apply(lambda x:len(x))#.hist()
bondlist = df_interestpay[(df_interestpay.len<=20)|(df_interestpay.len>=30)].index
df_interestpay = df_interestpay.loc[df_interestpay.index.isin(bondlist)]
df_interestpay[df_interestpay.index =='139415.SH'].利率说明.values

array(['4.39%'], dtype=object)

In [6]:
list1 = []
for i in range(2010,2022):
    for k in range(1,13):
        str1 = str(i)+'-'+str(k).zfill(2)
        list1.append(str1)
df0 = pd.DataFrame(index = list1)

In [8]:
def get_tax_rate_series(code = '1480527.IB'):
    df1 = df0.copy()
    df1[code] = 0
    text = df_interestpay.loc[df_interestpay.index == code]['利率说明'].values[0]
    paymonth = df_interestpay['付息日'][code]
    paymonth = int(paymonth[:paymonth.find('月')])
    qxyear = str(df_interestpay['起息日'][code])[:4]
    if len(text) <= 10:
        taxrate = float(text[:-1])
        for i in df1.index.tolist():
            if int(i[-2:]) ==  paymonth:
                if int(i[:4]) > int(qxyear):
                    df1[code][i] = taxrate
#        return df1
    elif len(text) >= 30:
        list1 = text.split(';')
#         print(list1)
        #listdate = [(i[:4]+'-'+i[4:6]+'-'+i[6:8]) for i in list1]
        startmonthlist = [(i[:4]) for i in list1]
        endmonthlist = [(i[9:13]) for i in list1]
#         print(startmonthlist)
#         print(endmonthlist)
        list2 = [i.find(':')+1 for i in list1]
        list3 = [i.find('%') for i in list1]
        dict1 = {}
        for i in range(len(list1)):
            dict1[startmonthlist[i]] = float(list1[i][list2[i]:list3[i]])
#         print(dict1)
        for i in df1.index.tolist():
            year = int(i[:4])
            month = int(i[-2:])
#             print(1)
            if int(i[-2:]) ==  paymonth:
                if year<int(startmonthlist[0]):
                    taxrate = 0
                else:
                    for j in range(len(list1)):

                        if int(startmonthlist[j])< year and int(endmonthlist[j] )>=year:
                            taxrate = dict1[startmonthlist[j]]
#                             print(taxrate)
                df1[code][i] = taxrate
    else:
        print('!!!')
    return df1[code]
a = get_tax_rate_series()
#a.to_excel('demo2.xlsx')

In [ ]:
df_total_tax = df0.copy()
for i in bondlist:
#     print(i)
    s1 = get_tax_rate_series(i)
    df_total_tax =pd.concat([df_total_tax,s1],axis = 1)

In [ ]:
dfinterest = (df_net_price.shift(1)*df_total_tax)/100

#### 债券复权价格 = (初始净值 - 现在净值)+现在全价 +利息累计支出

In [304]:
(-df_net_price+100+dfprice+dfinterest.cumsum()).to_excel('FINALPRICE.)

,58028,038006.IB,058028.00,058032.IB,068005.BC,068005.IB,068012.BC,068012.IB,068015.BC,068015.IB,...,Q16060707.SH,Q16060815.SH,Q16081814.SH,Q17042012.SH,Q17072503.SH,Q18091405.SH,Q19011716.SH,Q19080704.SH,Q19112517.SH,Q21120113.SH
Date,,,,,,,,,,,,,,,,,,,,,
2010-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-02,NaN,NaN,NaN,91.4426,NaN,94.3188,NaN,93.5203,NaN,92.4451,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-03,NaN,99.2147,NaN,93.6769,NaN,96.4762,NaN,95.7124,NaN,94.6293,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-04,NaN,101.1587,NaN,94.9619,NaN,97.4296,NaN,96.6637,NaN,95.5776,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-05,NaN,102.1423,NaN,96.5466,NaN,98.9987,NaN,98.2233,NaN,97.1248,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-11,NaN,169.3175,NaN,159.9876,157.1394,157.1394,155.774,155.7740,154.9450,154.9450,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2021-12,NaN,170.4268,NaN,160.9599,158.1464,158.1464,156.779,156.7790,155.9366,155.9366,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [302]:
# ((-df_net_price+100+dfprice+dfinterest.cumsum()))['1724005.IB'].tail(30)

In [300]:
# ((-df_net_price+100+dfprice))['1724005.IB'].tail(30)

In [ ]:
# df_advancepay = pd.read_excel('企业债提前还本信息.xlsx')
# df_advancepay.columns = ['证券代码', '证券简称', '提前还本日1', '提前还本日2',
#        '提前还本日3', '提前还本日4', '提前还本日5',
#        '提前还本日6', '提前还本日7',
#        '提前还本比例1', '提前还本比例2',
#        '提前还本比例3', '提前还本比例4',
#        '提前还本比例5', '提前还本比例6',
#        '提前还本比例7']
# df_advancepay.set_index('证券代码',inplace = True)

In [151]:
(-df_net_price+100+dfprice)['1724006.IB'].to_excel('demo.xlsx')

In [ ]:
# def fetch_price_minus(code = '1724006.IB',date = '2019-03',backmonth = 1):
#     df_return = (dfprice - dfprice.shift(backmonth))
#     return df_return[code][date]

# def payinterest(code = '1724006.IB',date = '2020-03',backmonth = 6):
#     #找出付息月
#     paymonth = df_interestpay['付息日'][code]
#     paymonth = int(paymonth[:paymonth.find('月')])
#     #找出持有月份
#     monthlist = calcrangedate(date = date,backmonth = backmonth)
#     monthlist1 = [int(i[-2:]) for i in monthlist]
#     #持有期间是否包含复习月找出持有月份
#     return paymonth in monthlist1

# def calcrangedate(date = '2019-03',backmonth = 1):
#     month = int(date[-2:])
#     #month1 = month -backmonth
#     list1 = []
#     for i in range(backmonth):
#         month1 = month-i
#         if month1 >= 1:
#             str1 = (date[:5]+str(month1).zfill(2))
#         else:
#             year = int(date[:4])
#             year1 = int(year) -1 
#             month1 = month1+12
#             str1 = (str(year1)+'-'+ str(month1).zfill(2))
#         list1.append(str1)
#     return list1
# calcrangedate(backmonth=12)

In [301]:
# def get_return(code,date,backmonth = 1):
#     #全价 - 上次全价
#     p1 = fetch_price_minus()
#     #判断是否需要付息
#     payint = payinterest(code = code,date date,backmonth = backmonth)
#     if not payint:
#         return p1
#     else:
#     #找出当期应付利息

#     #找出当期净值
    
#     #找出当期超额付息
    
#     #计算收益